### PR TITLE
Updated Info.php with accepted protocols

### PR DESCRIPTION
**Pull request by SuperMaXAleX**
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by erkam2002** [comment]
No

**Comment by Bruno99** [comment]
100 and 101protocol not support TradeVillager

**Comment by caspervanneck** [comment]
Nope @SuperMaXAleX

**Comment by SuperMaXAleX** [comment]
Bruh, do an another branch so

**Pull request closed without merging**
