### PR TITLE
[WIP] Reformatting

### PR DESCRIPTION
**Pull request by AppleDevelops**
## PR Description
**DO NOT MERGE THIS IS A WIP**

This PR aims to reformat code.
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by AppleDevelops** [comment]
After this, I will start working on API 3.1.0

**Comment by NFGamerMC** [comment]
Appl why are you helping him? Also if you are owner can I be added as owner again. I can't do anything but pull requests

**Comment by AppleDevelops** [comment]
@jrodr10 Please don't close this, I've spent a decent amount of time working on this.

**Comment by jrodr10** [comment]
I won't close it 👍

**Comment by AppleDevelops** [comment]
Thanks @jrodr10

**Comment by AppleDevelops** [comment]
@jrodr10 Add me back as a member please.

**Comment by jrodr10** [comment]
🤔 what is this ur aiming for

**Comment by AppleDevelops** [comment]
A commit

**Comment by AppleDevelops** [comment]
Merge it, @jrodr10.

**Comment by NFGamerMC** [comment]
GitHub says they are going to revert the deletion if the archive

**Comment by NycuRO** [comment]
@AppleDevelops WTF. NOT LIKE THAT FORMATING!

Use THIS FORMAT:

```public function forFormating($bla, $bla)
{

bla bla bla bla
}```

**Comment by AppleDevelops** [comment]
Are you mental?

**Comment by AppleDevelops** [comment]
You don't do PHPStorms formatting, I made a config to actually reformat it, not cause errors.

**Comment by jrodr10** [comment]
🤔 merge or nah

**Comment by jrodr10** [comment]
Add protocol hack back then I'll merge

**Comment by AppleDevelops** [comment]
Protocol hack does more damage

**Comment by NFGamerMC** [comment]
@AppleDevelops Check this, https://github.com/ServerSoftwareArchive-restored

GitHub gave the whole org to me!

**Comment by NFGamerMC** [comment]
I added a branch with all of your reformatting  work!

**Comment by NFGamerMC** [comment]
https://github.com/ServerSoftwareArchive-restored/Tesseract/tree/AppleDevelops-Reformat

**Comment by jrodr10** [comment]
🙄 this kid doesn't quit lmao

**Comment by jrodr10** [comment]
@AppleDevelops I'll take your word for it

**Comment by NycuRO** [comment]
@jrodr10 Fuck off man. You're fucking human.

**Comment by jrodr10** [comment]
@NycuRO why are you so mad.... idek you lol

**Comment by NycuRO** [comment]
@jrodr10 Fuck off bitch. This is not project, you steal all! Shut the fuck up!

**Comment by jrodr10** [comment]
🙄

**Pull request merged**
