### PR TITLE
Logo ASCII / Issue template

### PR DESCRIPTION
**Pull request by xZeroMCPE**
Fixed it, somehow i forgot to include something on gitshell

### CODE REVIEW

**Comment by TheAppleGamer** [comment]
Later on I'll update the template to look less like Genisys but this'll do for now!

**Comment by xZeroMCPE** [comment]
@TheAppleGamer True, also can i get added in? instead of me having to do PR's. 

If not it's okay lol.

**Comment by TheAppleGamer** [comment]
@xZeroMCPE I'll add you :)

**Comment by xZeroMCPE** [comment]
@TheAppleGamer Great.

**Comment by TheAppleGamer** [comment]
@xZeroMCPE There you go

**Comment by xZeroMCPE** [comment]
@TheAppleGamer Awesome.

**Comment by TheAppleGamer** [comment]
@xZeroMCPE Currently working on automatic builds lol

**Comment by xZeroMCPE** [comment]
@TheAppleGamer Good.

**Pull request merged**
