### PR TITLE
ItemFrame fix.

### PR DESCRIPTION
**Pull request by ISRAPIL**
## PR Description

Fix ItemFrame.

## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by ISRAPIL** [comment]
Give me contributor, I do not like to wait ...

**Comment by AppleDevelops** [comment]
Change TransferPacket import.

**Comment by ISRAPIL** [comment]
What? @AppleDevelops 
image

**Comment by AppleDevelops** [comment]
Get rid of the two new things you added

**Comment by ISRAPIL** [comment]
Ok. I'm delete it. @AppleDevelops

**Comment by ISRAPIL** [comment]
_**Is anybody here?**_

**Pull request merged**
