### PR TITLE
Fixed transaction bug?

### PR DESCRIPTION
**Pull request by EmreTr1**
## Fixed transaction bug?

- tested

### CODE REVIEW

**Comment by jrodr10** [comment]
Test this before we push it.

**Comment by JunkDaCoder** [comment]
i alreayd pr'ed this

**Comment by JunkDaCoder** [comment]
No didnt fix it

**Comment by AppleDevelops** [comment]
Don't make a PR without testing it and having no idea if it fixes it

**Comment by AppleDevelops** [comment]
Wrong button

**Comment by Prisane** [comment]
I tested it. putting item in chest improved

**Comment by EmreTr1** [comment]
I tested now. It working good.

**Comment by JunkDaCoder** [comment]
does it fix this issue? https://github.com/TesseractTeam/Tesseract/issues/329

**Comment by KairusDarkSeeker** [comment]
Wtf it even made it worse, I can't grab items from the inventory

**Comment by KairusDarkSeeker** [comment]
Revert this please

**Pull request merged**
