### PR TITLE
Add 1.0.0 Elements and Fix a Bag

### PR DESCRIPTION
**Pull request by Nought57**
Add EndBlocks
Add PurpurBlocks
Add ChorusBlocks
My Branch Test Passing

### CODE REVIEW

**Comment by Nought57** [comment]
My pull request no problem, my Tesseract master-branch test passing.
This error is default master-branch bag.
Please read Travis CI log files

PHP Parse error:  syntax error, unexpected ')', expecting ']' in src/pocketmine/command/defaults/GamemodeCommand.php on line 83
Parse error: syntax error, unexpected ')', expecting ']' in src/pocketmine/command/defaults/GamemodeCommand.php on line 83
Errors parsing src/pocketmine/command/defaults/GamemodeCommand.php

PMMP Chunk format from Elywings marged master-branch problem.
master-branch Starting Crashed.

**Comment by Nought57** [comment]
fix a Gamemode bag and LightPopulation bag.

**Comment by Nought57** [comment]
Main master-branch using Test Passing.
Please marge pull request.

**Comment by Nought57** [comment]
Test

**Comment by Nought57** [comment]
Next planning to add 1.0.0 Items and 1.0.0 Entity.

**Comment by Nought57** [comment]
Add PurpurStairs and Update PurpurBlock ID's

**Comment by Nought57** [comment]
Update latest version resources lang files

**Comment by Nought57** [comment]
#69 #72 Other modification points.
Disable checkBlockCollision function.

**Comment by Nought57** [comment]
Change the echo to logger, Server Stop Message

**Comment by Nought57** [comment]
Add server stop threads count

**Comment by Nought57** [comment]
Add ChorusFruit Item

**Comment by Nought57** [comment]
Update Unknown Name to Item Name

**Comment by xZeroMCPE** [comment]
@Nought57 The problem was a syntax issue on the gamemode command -.-

I fixed that... Jenkins builds are successfully working now.

**Comment by Nought57** [comment]
@xZeroMCPE Look at Travis CI please, This Commit failed.

PHP Parse error:  syntax error, unexpected '}', expecting end of file in src/pocketmine/command/defaults/GamemodeCommand.php on line 91
Parse error: syntax error, unexpected '}', expecting end of file in src/pocketmine/command/defaults/GamemodeCommand.php on line 91
Errors parsing src/pocketmine/command/defaults/GamemodeCommand.php
PHP Parse error:  syntax error, unexpected '}', expecting end of file in src/pocketmine/command/defaults/GamemodeCommand.php on line 91
Parse error: syntax error, unexpected '}', expecting end of file in src/pocketmine/command/defaults/GamemodeCommand.php on line 91
Errors parsing src/pocketmine/command/defaults/GamemodeCommand.php

Please use My Commit "Fix a crash bug".

**Pull request merged**
