### PR TITLE
Add 1.0.0 Blocks (New Element 1.0.0)

### PR DESCRIPTION
**Pull request by Nought57**
Add New Blocks (EndBlocks, PurpurBlocks, ChorusBlocks)
New Blocks add Creative Inventory

### CODE REVIEW

**Comment by Nought57** [comment]
Next planning to add 1.0.0 Items

**Comment by caspervanneck** [comment]
@Nought57 and ender chest?

**Comment by Nought57** [comment]
fix a ChorusFlower.php

**Comment by Nought57** [comment]
fix a ChorusFlower.php

**Comment by Nought57** [comment]
Misstake, Before correction failes upload.
Re send fix version pull requests.

**Comment by Nought57** [comment]
@caspervanneck I'll try it. Please wait until correspondence.

**Pull request closed without merging**
