### PR TITLE
Here ya go, plugin devs!

### PR DESCRIPTION
**Pull request by remotevase**
## PR Description
DON't MERGE YET! Still testing.
## Have you tested it?
- [ ] I have tested it.
- [x] I have not tested it.
...

### CODE REVIEW

**Comment by remotevase** [comment]
Please squash and merge once it is tested. I am unable to test.

**Comment by remotevase** [comment]
@xZeroMCPE can you test/

**Comment by xZeroMCPE** [comment]
@remotevase I"ll try.

**Comment by AppleDevelops** [comment]
Stolen from PMMP

**Pull request closed without merging**
