### PR TITLE
Start adding in elytra

### PR DESCRIPTION
**Pull request by remotevase**
NOT READY YET! Will be finished very soon!

### CODE REVIEW

**Comment by AppleDevelops** [comment]
Elytras aren't blocks

**Comment by remotevase** [comment]
oops

**Comment by remotevase** [comment]
:P

**Comment by remotevase** [comment]
I'm just not sure where to put the files...

**Comment by xZeroMCPE** [comment]
its an Item....

**Comment by remotevase** [comment]
Yes but also there is the actions (like the graceful falling) there is another file that goes along with it, so would that go in math or something?

**Comment by remotevase** [comment]
On second thought I may be able to combine the two files...

**Comment by AppleDevelops** [comment]
class not interface

**Comment by Ad5001** [comment]
Sorry, but this code is taken from http://github.com/Ad5001/Elytra licensed  under the Creative Common Attribution-NoCommercial-ShareAlike v4 International and many things off the section 3 of the license hasn't been actually completed:

Section 3 – License Conditions.

Your exercise of the Licensed Rights is expressly made subject to the following conditions.

Attribution.

If You Share the Licensed Material (including in modified form), You must:

retain the following if it is supplied by the Licensor with the Licensed Material:
identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
a copyright notice;
a notice that refers to this Public License;
a notice that refers to the disclaimer of warranties;
a URI or hyperlink to the Licensed Material to the extent reasonably practicable;
indicate if You modified the Licensed Material and retain an indication of any previous modifications; and
indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.
You may satisfy the conditions in Section 3(a)(1) in any reasonable manner based on the medium, means, and context in which You Share the Licensed Material. For example, it may be reasonable to satisfy the conditions by providing a URI or hyperlink to a resource that includes the required information.
If requested by the Licensor, You must remove any of the information required by Section 3(a)(1)(A) to the extent reasonably practicable.
ShareAlike.
In addition to the conditions in Section 3(a), if You Share Adapted Material You produce, the following conditions also apply.

The Adapter’s License You apply must be a Creative Commons license with the same License Elements, this version or later, or a BY-NC-SA Compatible License.
You must include the text of, or the URI or hyperlink to, the Adapter's License You apply. You may satisfy this condition in any reasonable manner based on the medium, means, and context in which You Share Adapted Material.
You may not offer or impose any additional or different terms or conditions on, or apply any Effective Technological Measures to, Adapted Material that restrict exercise of the rights granted under the Adapter's License You apply.

**Comment by Nought57** [comment]
@Ad5001 May I ask question??
You are saying against me of my pull request ("Add 1.0.0 Item") ??

**Comment by Ad5001** [comment]
@Nought57 I don't know for yours but I'm 100% sure that this pull request takes my code (and modifies it but that doesn't change anything thought the license).
If your pull request is based on this one, it, then, also include yours.

**Comment by Nought57** [comment]
@Ad5001 Why your 100% sure that?? My pull request code is original. 
Not using your codes. This code is created based on Pocket-Mine.

**Comment by remotevase** [comment]
Yesterday, I wrote in #73  that I will use my own code. No need to be mad

**Comment by remotevase** [comment]
Tested, it works!

**Pull request merged**
