### PR TITLE
Fix Login Timeout

### PR DESCRIPTION
**Pull request by SuperMaXAleX**
## PR Description
Sounds are back. For true.
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by AnkitM252** [comment]
Why closed?

**Comment by Driesboy** [comment]
idk

**Comment by AppleDevelops** [comment]
Because it doesn't actually fix the issue, resourcepackinfopacket needs an update

**Comment by NFGamerMC** [comment]
Still. it helps

**Comment by AppleDevelops** [comment]
Alright, your stupidity, not mine.

**Comment by NFGamerMC** [comment]
We didn't merge this for a reason, I opened it because I could make changes to it

**Comment by SuperMaXAleX** [comment]
I pushed on the wrong button lmao

**Comment by Driesboy** [comment]
ow ok

**Pull request closed without merging**
