### PR TITLE
Protocol hack

### PR DESCRIPTION
**Pull request by xZeroMCPE**
## PR Description

Accepts multiple version of MCPE... 

## Have you tested it?
- [ ] I have tested it.
- [x] I have not tested it.
...

### CODE REVIEW

**Comment by remotevase** [comment]
Noooooo whhhyyyy we don't like hacks

**Comment by ISRAPIL** [comment]
It's a not hack... MultyProtocol(1.0.x).

**Comment by SuperMaXAleX** [comment]
@xZeroMCPE Don't forgot to add credit to Elywing

**Comment by xZeroMCPE** [comment]
@SuperMaXAleX It was not copied from their....  tbh, i have not visited ElyWing repo for weeks..

**Pull request merged**
