### PR TITLE
PMMP PORTS

### PR DESCRIPTION
**Pull request by JunkDaCoder**
## Have you tested it?
- [ x] I have tested it.
- [ ] I have not tested it.
...
I simple ported over PMMP's way of handling item pickups/dropups and its fixed the issue, nor errors or anything thrown. Issue is https://github.com/TesseractTeam/Tesseract/issues/329

### CODE REVIEW

**Comment by JunkDaCoder** [comment]
Why was it closed?

**Comment by SuperMaXAleX** [comment]
Copy paste.

**Comment by archie426** [comment]
And you wander why I want you to shut this down -_-

**Comment by jrodr10** [comment]
Your thoughts? @AppleDevelops close this? Or merge

**Comment by AppleDevelops** [comment]
@jrodr10 Close it, causes issues and it's copy and paste.

**Pull request closed without merging**
