### PR TITLE
Ban handled by ban function and not /ban

### PR DESCRIPTION
**Pull request by Dog2puppy**
## PR Description
This PR only applies to /ban. /banip and Genisys ban commands are not affected by this PR. 
## Have you tested it?
- [ ] I have tested it.
- [x] I have not tested it.
...

### CODE REVIEW

**Comment by RTGDaCoder** [comment]
Maybe, you can implement the "Ban Reason" stated here at #212 by interpreting the arguments.

**Comment by Dog2puppy** [comment]
I'll try to do that in another PR.

**Comment by AnkitM252** [comment]
Should this be merged?

**Comment by AppleDevelops** [comment]
It needs actual testing

**Pull request merged**
