### PR TITLE
Fix More in Generator + Now Nether Generator Work.

### PR DESCRIPTION
**Pull request by NycuRO**
## PR Description
This PR changes more and add more in Generators Normal and FIX Nether Generator.
## Have you tested it?
- [x] I have tested it.
- [] I have not tested it.
...

### CODE REVIEW

**Comment by xZeroMCPE** [comment]
Test it. Confirm to me it works.

**Comment by AppleDevelops** [comment]
@xZeroMCPE Do you actually spawn in the nether?

**Comment by NycuRO** [comment]
Why i'm moved file?

Because i don't search where is problem. Generator task RIP because isn't Populator in "normal\populators".

**Comment by NycuRO** [comment]
Ready, you can accept. @xZeroMCPE @AppleDevelops

**Comment by AnkitM252** [comment]
There are errors left!

**Comment by NycuRO** [comment]
@AnkitM252 Ready.

**Comment by NycuRO** [comment]
Now you can accept.

**Comment by AnkitM252** [comment]
Its not generating the nether world.

**Comment by NycuRO** [comment]
@AnkitM252 With portal, no. Because isn't added code. But now generated with one plugin: MultiWorld or other.

**Comment by NycuRO** [comment]
Create world with one plugin and generator now works if you teleported.

**Pull request merged**
