### PR TITLE
1.1 Pre-Support Update

### PR DESCRIPTION
**Pull request by FunnyBuddys**
## PR Description
1.1 Update
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by NFGamerMC** [comment]
Copier.

**Comment by FunnyBuddys** [comment]
No..

**Comment by akaSnapy** [comment]
Someone was able to update it and u don't agree, this project is fucked up

**Comment by FunnyBuddys** [comment]
The Fucking Bitches Steal the Repo and deleted the Real Owners. The Fake Owner is Fucked up and not the Project

**Comment by akaSnapy** [comment]
They arent capable to update it to 1.1 smh, this project will die

**Comment by FunnyBuddys** [comment]
If you want the old Owners back: https://twitter.com/AppleDevelops/status/870871766377394176

**Comment by akaSnapy** [comment]
I did

**Comment by EoflaOE** [comment]
@FunnyBuddys, Please do not use swear words.

**Comment by FunnyBuddys** [comment]
@jrodr10 Should give @AppleDevelops and @ImagicalGamer their Owner back.

**Comment by andris155** [comment]
Tested and not work this.

**Comment by FunnyBuddys** [comment]
@andris155 i fixed some Bugs. You can test it by my Repo.

**Comment by andris155** [comment]
kepkivagas

**Comment by andris155** [comment]
Raklib not work.  (raklib-disable: false)
kepkivagas

**Comment by EoflaOE** [comment]
@andris155 Please re-download the latest version of Tesseract on GitHub! My commit for tesseract_eng.yml fixes your issue.

**Pull request closed without merging**
