### PR TITLE
API 4.0.0

### PR DESCRIPTION
**Pull request by AppleDevelops**
API 4.0.0 is for cleanups, and hopefully fixes.
We hope to add more features in this.

Use this branch at your own risk!

We do need testers!

### CODE REVIEW

**Comment by ISRAPIL** [comment]
More and 3 api is not finished

**Comment by AppleDevelops** [comment]
We're ahead of PMMP's API, we're doing major changes in a new api that comes out after 1.1 is released.

**Comment by Nought57** [comment]
I'm sorry.

**Comment by Sandertv** [comment]
Ermm, could I just question why you bumped API to 4.0.0 if API 3.0.0 isn't even finalized and still in ALPHA state? Seems a bit weird to me.

**Comment by AppleDevelops** [comment]
This isn't PocketMine

**Comment by Sandertv** [comment]
Ignore me, I should stop mixing in. Sorry.

**Comment by AppleDevelops** [comment]
I'll help with that

**Comment by xZeroMCPE** [comment]
Will be re-making the API 4.0.0 branch.... seems to be a mess

**Comment by jrodr10** [comment]
This still being worked on @AppleDevelops ? 👀

**Comment by AppleDevelops** [comment]
Nope @jrodr10, give me write access to the branch, and I'll work on API 3.2

**Pull request closed without merging**
