### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by RTGDaCoder**
Added several Weather fixes and an error fix!

I haven't test this yet. Of course, this needs some fix. I'm sure someone will be able to spot those :)

### CODE REVIEW

**Comment by RTGDaCoder** [comment]
Fixes #408 too

**Comment by ImagicalGamer** [comment]
Please test and insure this is working.

**Comment by NycuRO** [comment]
-_- Ok, is optimizate but not correct.

**Comment by RTGDaCoder** [comment]
If you guys find any flaw, please let me know.. I can't find any

**Comment by Driesboy** [comment]
`TypeError: "Argument 2 passed to pocketmine\level\weather\Weather::__construct() must implement interface pocketmine\level\format\io\LevelProvider, integer given, called in /home/travis/build/TesseractTeam/Tesseract/src/pocketmine/level/Level.php on line 406" (EXCEPTION) in "/src/pocketmine/level/weather/Weather" at line 34`

**Comment by RTGDaCoder** [comment]
@Driesboy Ok, noted

**Pull request closed without merging**
