### PR TITLE
Action bar

### PR DESCRIPTION
**Pull request by xZeroMCPE**
## PR Description

This is similar to "Title" on Spigot / Bukkit

Image

Very useful for developers! (or server owners, wanting MCPC features)

Don't merge yet!

## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by ISRAPIL** [comment]
Ок...

image

**Comment by Cheloveck1** [comment]
ISRAPIL, топ же

**Comment by xBeeegsone** [comment]
Not working

**Comment by remotevase** [comment]
Nice, its a feature that other servers dont have

**Comment by xZeroMCPE** [comment]
@ISRAPIL Try testing it now. Make sure you pass true for window 10 like;

$player->sendActionBar("Hello", true);

I've added that for (maybe) debugging purpose...

**Comment by xZeroMCPE** [comment]
I think i broke the branch lol.... Someone fix it.... Busy rn...

**Comment by remotevase** [comment]
Lol wow I'll try to fix it later after IRL stuff XD

**Comment by xZeroMCPE** [comment]
@remotevase Alright thanks. Much, appreciation.

**Comment by remotevase** [comment]
DAMN IT WHY DID I DO THAT?! I DIDNT MEAN TO

**Comment by remotevase** [comment]
now i gotta find a way to revert

**Pull request merged**
