### PR TITLE
im tired of noobs ;-;

### PR DESCRIPTION
**Pull request by TDMidkwhatisxd**
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by TDMidkwhatisxd** [comment]
there were no changes in protocol , lol, all you edited is protocol info, so it should be fine!

**Comment by TDMidkwhatisxd** [comment]
I give up, mess tesseract as u wish, I think imma go on bluelight on 1.1.0, I'm done

**Comment by EoflaOE** [comment]
Please stop messing up Tesseract.

**Comment by AppleDevelops** [comment]
If I could come back, this would be great b

**Comment by NFGamerMC** [comment]
@AppleDevelops @TDMidkwhatisxd @EoflaOE @hmy2001 @Enes5519 @TesseractTeam/software @TesseractTeam/owners **GitHub is restoring the old repo "ServerSoftwareArchive, I am currently seeing it up. We can move back and stay back! Tesseract is almost dead and someone needs to save it or we will not go down as a stable software, we will un-willingly (think that's a word) be forced to shut down Tesseract!**

Thanks @jrodr10,
You have broken Tesseract and slowed down production on 100+ servers worldwide!

**Comment by NFGamerMC** [comment]
I am moving to BlueLight and Glowstone Edge until this is over, all I am getting is nothing because a nine year old who can't code took it over because he was "scared" of it getting deleted. Little did he know that it is new deleted and that GitHub saves all that stuff in there database. I asked!

**Comment by TDMidkwhatisxd** [comment]
welcome back apple <3

**Pull request closed without merging**
