### PR TITLE
adding bin folder to tesseract (helps with start.cmd)

### PR DESCRIPTION
**Pull request by IISweePII**
wip, making a folder (i dont really know how xD)

### CODE REVIEW

**Comment by IISweePII** [comment]
the start.cmd was not loading when the source code was attempted to be downloaded, since the bin was missing, so I added the folder and put files in

**Comment by xZeroMCPE** [comment]
Seems useless...

**Comment by IrishPacks** [comment]
I'd say to not do this and link to an external source to download the PHP binaries in the README.md.

**Comment by AppleDevelops** [comment]
Not needed

**Comment by IISweePII** [comment]
@xZeroMCPE @AppleDevelops I thought of adding a bin folder because in the tesseract source code rn there is a start.cmd that does not work. I thought adding a bin would make it work and allow them to run a server under tesseract

**Comment by IISweePII** [comment]
@IrishPacks it's only a test as well to see if stuff would work through, through the CI it doesn't catch anything

**Comment by IISweePII** [comment]
Eh, I'll just ignore this PR, was worth a try I guess

**Pull request closed without merging**
