### PR TITLE
Update ci.sh for artifacts

### PR DESCRIPTION
**Pull request by ondraczsk**
at my software this works

### CODE REVIEW

**Comment by XxParkerGamesxX** [comment]
well the build failed so your software must not work @ondraczsk

**Comment by ondraczsk** [comment]
look on github.com/imagicalminereactive/imagicalmine and look on travis @XxParkerGamesxX it works

**Comment by ondraczsk** [comment]
plz dont close this pr, im working on it

**Comment by AppleDevelops** [comment]
Move this with the other PR

**Pull request closed without merging**
