### PR TITLE
Its Android not ODROID. LOL XD

### PR DESCRIPTION
**Pull request by Qimie**
## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by Matthww** [comment]
So stupid

**Comment by Qimie** [comment]
Im stupid or Linux or other?

**Comment by Matthww** [comment]
@Qimie You are

**Comment by Matthww** [comment]
Also read the whole message

**Comment by Qimie** [comment]
Im done with life. xd

**Pull request merged**
