### PR TITLE
multi protocol......

### PR DESCRIPTION
**Pull request by djdisodo**
## Have you tested it?
- [ ] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by djdisodo** [comment]
The last merge was my mistake.

**Comment by shdudwns** [comment]
What is good with multi protocol?

**Comment by caspervanneck** [comment]
why are my commits from my repo coppyd

**Comment by mal0ne-23** [comment]
you are officially fucking retarded!

**Pull request closed without merging**
