### PR TITLE
Add Forums and Readme Fixes!

### PR DESCRIPTION
**Pull request by TesseractTeamForum**
### PR Description
Hey jrodr10 make sure to read the comment in the readme code. This will give you instructions on making an Admin account.
---
I will be hosting this myself at no cost in a high performance DigitalOcean VPS! You can comment in this if you have any questions. Do not close this until you have checked out forums and read the code!

### Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by MCPEGamerJPatGitHub** [comment]
Is it only me that thinks this is just NF being stupid and making a new account

**Comment by NFGamerMC** [comment]
@MCPEGamerJPatGitHub Can you please tell me who NF is?

**Comment by TesseractTeamForum** [comment]
@MCPEGamerJPatGitHub Who the hell is NF?

**Comment by TesseractTeamForum** [comment]
Also, this is not my mail account. This is what I use to setup the forums

**Comment by caspervanneck** [comment]
hi

**Comment by TesseractTeamForum** [comment]
@caspervanneck Can you tell me who NF is? @MCPEGamerJPatGitHub Won't tell me who he is?

**Comment by NFGamerMC** [comment]
@TesseractTeamForum What is wrong with me, I stranded up for the real owners!

**Comment by KairusDarkSeeker** [comment]
He just wants your plugins guys, I'd rather host on my own plus this isn't an advertising site so close this issue

**Comment by TesseractTeamForum** [comment]
@KairusDarkSeeker Can you even read, I said that I was adding something like on forums.pmmp.io that will allow you to request plugins from developers. I don't want others plugins I like to be original. Please go [here](https://weallcanread.com/phonics-for-adults/) to learn how to read.

**Comment by jrodr10** [comment]
🙄 nf go away

**Pull request closed without merging**
