### PR TITLE
Resource pack

### PR DESCRIPTION
**Pull request by XxParkerGamesxX**
## Have you tested it?
- [works really good I like it ] I have tested it.  
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by caspervanneck** [comment]
That are my commits ?

**Comment by XxParkerGamesxX** [comment]
You know me ill help out alot i want a good software that works really good adding me will make that happen remember i have my diploma for Computer Science
So im really good at this stuff

**Comment by NFGamerMC** [comment]
@XxParkerGamesxX No one cares if you have a stupid diploma in Computer Science. What you did also shows that no one can trust you.

**Comment by jrodr10** [comment]
Running lint...
PHP Fatal error:  Cannot declare class Volatile, because the name is already in use in src/spl/stubs/pthreads.php on line 72
Fatal error: Cannot declare class Volatile, because the name is already in use in src/spl/stubs/pthreads.php on line 72
Errors parsing src/spl/stubs/pthreads.php
The command "./ci.sh" exited with 1.

**Comment by caspervanneck** [comment]
@jrodr10 travis bug

**Comment by Pizzahaet** [comment]
haha L

**Comment by jrodr10** [comment]
🙄

**Comment by XxParkerGamesxX** [comment]
Lol holy fuck you say I'm 10 well i would like to be 9 yrs younger thanks at least I don't have autism people have donated they got what they paid for so NfGamer fuck off and please dont print your shitty code off the internet i dont copy i only type and paste on github now please bitch shut the fuck up or shit will happen

**Comment by Pizzahaet** [comment]
@XxParkerGamesxX Shut up fake fuck, don't make me add links proving your copy pasta, if you are going to copy and paste at least give credit to original developers and not claim it as yours!

**Comment by Pizzahaet** [comment]
@XxParkerGamesxX It is obvious you can't even edit a simple .md that is obvious at the beginning of the issue

**Comment by NFGamerMC** [comment]
Send the links please, will expose him.

**Comment by Pizzahaet** [comment]
https://github.com/XxParkerGamesxX/GalacticGenisys/commits/master 
any commits of his are obviously copy pasta

**Comment by Pizzahaet** [comment]
@NFGamerMC It is obvious he can't code, he doesn't even know how to upload an Archive to github so it auto extracts...

**Comment by NFGamerMC** [comment]
Any more dirt on him? He is a joke. Even I can code better than him

**Comment by caspervanneck** [comment]
and i sorry for menging with it

**Comment by Pizzahaet** [comment]
@NFGamerMC Any commits anywhere of his, he obviously copied from somewhere in the trillions of terabytes of the internet

**Pull request closed without merging**
