### PR TITLE
Finished Anvils!

### PR DESCRIPTION
**Pull request by ImagicalGamer**

### CODE REVIEW

**Comment by ImagicalGamer** [comment]
Possible anvil bugs don't merge.

**Comment by ISRAPIL** [comment]
You have all the commits finished...

**Comment by ImagicalGamer** [comment]
AnvilProcessEvent isn't being called for some reason.

**Comment by bulutsun** [comment]
Please fix enchantment tables.

**Comment by ISRAPIL** [comment]
What  error? @bulutsun

**Comment by bulutsun** [comment]
When the Enchant is doing the things are falling.

**Pull request closed without merging**
