### PR TITLE
Immature.

### PR DESCRIPTION
**Pull request by Pogogo007**
Seriously Linux.

### CODE REVIEW

**Comment by Pogogo007** [comment]
@jrodr10 You do not jack someone elses work, you do not change the codename to RottenApple because thats just plain stupid.

**Comment by Pogogo007** [comment]
@jrodr10 plus someone had to do it because no one would. It made you look VERY unprofessional.

**Comment by Pogogo007** [comment]
@jrodr10 and at least @caspervanneck knows how to code and doesnt steal peoples stuff

**Comment by NFGamerMC** [comment]
@Pogogo007 You should try having a better look, @caspervanneck steals code all the time

**Comment by Pogogo007** [comment]
@NFGamerMC well looks like everybody working on Tesseract steals code now!

**Comment by Pogogo007** [comment]
@NFGamerMC except Jake

**Comment by caspervanneck** [comment]
@NFGamerMC if you dont steal code and i give cradit for it

**Comment by caspervanneck** [comment]
@NFGamerMC your weak you say it to child from 15 -_-

**Comment by NFGamerMC** [comment]
@caspervanneck Yes, you do steal code. You just need a few lessons on Copyright and you will be ready to go. You can write PHP but you always make like 100 commits.

**Comment by caspervanneck** [comment]
yes @NFGamerMC uhm do you want hoin blackmine help me out and sorry um yes am not the best codder if look at my profiel

**Comment by NFGamerMC** [comment]
You are better at PHP then me. Anyways sorry if you took that as a threat

**Comment by caspervanneck** [comment]
@NFGamerMC have discord  then we chat there on blackmine group

**Comment by NFGamerMC** [comment]
@caspervanneck Okay, I will be doing a lot of work to BlackMine. Can we also discuss changing the name because everyone thinks that we are copying ImagicalMine/BlueLight

**Comment by caspervanneck** [comment]
o yes @NFGamerMC do you know a good name

**Comment by AppleDevelops** [comment]
About the code stealing, it's true, all of the code you guys have added are from Genisys, PMMP, or BlueLight, you guys can't even spell properly at this point, let alone maintain a software

**Comment by ImagicalGamer** [comment]
I think codename RottenApple was fine, Tesseract was rotten and Apple was the primary developer.

**Comment by caspervanneck** [comment]
@AppleDevelops what ever you deleted your groups so yea

**Comment by AppleDevelops** [comment]
It's better than copying and pasting every update like you fools

**Pull request merged**
