### PR TITLE
error

### PR DESCRIPTION
**Pull request by SuperKali**
Warning: yaml_parse(): scanning error encountered during parsing: found characte            r that cannot start any token (line 132, column 1), context while scanning for t            he next token (line 132, column 1) in /root/Nuova cartella/src/pocketmine/utils/            Config.php on line 143

Warning: yaml_parse(): scanning error encountered during parsing: found characte            r that cannot start any token (line 132, column 1), context while scanning for t            he next token (line 132, column 1) in /root/Nuova cartella/src/pocketmine/utils/            Config.php on line 143
[Tesseract] [20:46:45] INFO> Everything seems to be alright! Server started!
[Tesseract] [20:46:45] CRITICAL> ClassNotFoundException: "Class pocketmine\netwo            rk\mcpe\protocol\DataPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader"             at line 144
[Tesseract] [20:46:45] EMERGENCY> An unrecoverable error has occurred and the se            rver has crashed. Creating a crash dump
[Tesseract] [20:46:45] CRITICAL> Error: "Call to a member function getPlugins()             on null" (EXCEPTION) in "/src/pocketmine/CrashDump" at line 197

### CODE REVIEW

**Comment by andris155** [comment]
https://github.com/FunnyBuddys/NewTesseract/commit/bc46912384ea2648274eec5408ddb06423e65731

**Comment by jrodr10** [comment]
Please pull to tesseract-1.1

**Comment by jrodr10** [comment]
@SuperKali fix the query this guy did most of the work and I'm a Java developer not PHP

**Comment by FunnyBuddys** [comment]
Wow...Seriously?

**Comment by FunnyBuddys** [comment]
Make me to a Member @jrodr10

**Pull request merged**
