### PR TITLE
Biome generator

### PR DESCRIPTION
**Pull request by Nought57**
Update Biome generator and Delete Normal2 data.
This biome bug, No server test.
If to cause New bug. As soon as possible, need revert.
#84 I fixed that (Only one part). successfully working now.

### CODE REVIEW

**Comment by Infernus102** [comment]
#86?

**Comment by Infernus102** [comment]
Build failed

**Comment by Nought57** [comment]
Update now.

**Comment by Infernus102** [comment]
Does it fix #86?

**Comment by Nought57** [comment]
@Infernus102 Verification in progress.

**Comment by xZeroMCPE** [comment]
@Nought57 Great, and for all other future PR's you submit, Try testing them. It would make things more easy for us.

**Pull request merged**
